// <auto-generated />
using System;
using BusinessLogic.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BusinessLogic.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250613140538_FixIdentity")]
    partial class FixIdentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BusinessLogic.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FavoriteFood")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("BusinessLogic.Models.Order", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("OrderId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<float>("Rating")
                        .HasColumnType("real");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            OrderDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 4.8f,
                            Status = 0,
                            UserName = "Guest"
                        });
                });

            modelBuilder.Entity("BusinessLogic.Models.OrderItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("OrderItemId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<float>("Rating")
                        .HasColumnType("real");

                    b.Property<long>("RecipeId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("RecipeId");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            OrderId = 1L,
                            Quantity = 2,
                            Rating = 0f,
                            RecipeId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            OrderId = 1L,
                            Quantity = 1,
                            Rating = 0f,
                            RecipeId = 2L
                        });
                });

            modelBuilder.Entity("BusinessLogic.Models.Recipe", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("RecipeId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("CaloriesPerServing")
                        .HasColumnType("int");

                    b.Property<int>("CookTimeMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Cuisine")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "image");

                    b.Property<string>("Ingredients")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("MealType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrepTimeMinutes")
                        .HasColumnType("int");

                    b.Property<float>("Rating")
                        .HasColumnType("real");

                    b.Property<int>("Servings")
                        .HasColumnType("int");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CaloriesPerServing = 300,
                            CookTimeMinutes = 15,
                            Cuisine = "Italian",
                            Difficulty = 0,
                            ImageUrl = "https://cdn.dummyjson.com/recipe-images/1.webp",
                            Ingredients = "Pizza dough\nTomato sauce\nFresh mozzarella cheese\nFresh basil leaves\nOlive oil\nSalt and pepper to taste",
                            Instructions = "Preheat the oven to 475°F (245°C).\nRoll out the pizza dough and spread tomato sauce evenly.\nTop with slices of fresh mozzarella and fresh basil leaves.\nDrizzle with olive oil and season with salt and pepper.\nBake in the preheated oven for 12-15 minutes or until the crust is golden brown.\nSlice and serve hot.",
                            MealType = "[\"Dinner\"]",
                            Name = "Classic Margherita Pizza",
                            PrepTimeMinutes = 20,
                            Rating = 4.6f,
                            Servings = 4,
                            Tags = "Pizza\nItalian",
                            UserId = 166
                        },
                        new
                        {
                            Id = 2L,
                            CaloriesPerServing = 250,
                            CookTimeMinutes = 20,
                            Cuisine = "Asian",
                            Difficulty = 1,
                            ImageUrl = "https://cdn.dummyjson.com/recipe-images/2.webp",
                            Ingredients = "Tofu, cubed\nBroccoli florets\nCarrots, sliced\nBell peppers, sliced\nSoy sauce\nGinger, minced\nGarlic, minced\nSesame oil\nCooked rice for serving",
                            Instructions = "In a wok, heat sesame oil over medium-high heat.\nAdd minced ginger and garlic, sauté until fragrant.\nAdd cubed tofu and stir-fry until golden brown.\nAdd broccoli, carrots, and bell peppers. Cook until vegetables are tender-crisp.\nPour soy sauce over the stir-fry and toss to combine.\nServe over cooked rice.",
                            MealType = "[\"Lunch\"]",
                            Name = "Vegetarian Stir-Fry",
                            PrepTimeMinutes = 15,
                            Rating = 4.7f,
                            Servings = 3,
                            Tags = "Vegetarian\nStir-fry\nAsian",
                            UserId = 143
                        },
                        new
                        {
                            Id = 3L,
                            CaloriesPerServing = 150,
                            CookTimeMinutes = 10,
                            Cuisine = "American",
                            Difficulty = 0,
                            ImageUrl = "https://cdn.dummyjson.com/recipe-images/3.webp",
                            Ingredients = "All-purpose flour\nButter, softened\nBrown sugar\nWhite sugar\nEggs\nVanilla extract\nBaking soda\nSalt\nChocolate chips",
                            Instructions = "Preheat the oven to 350°F (175°C).\nIn a bowl, cream together softened butter, brown sugar, and white sugar.\nBeat in eggs one at a time, then stir in vanilla extract.\nCombine flour, baking soda, and salt. Gradually add to the wet ingredients.\nFold in chocolate chips.\nDrop rounded tablespoons of dough onto ungreased baking sheets.\nBake for 10-12 minutes or until edges are golden brown.\nAllow cookies to cool on the baking sheet for a few minutes before transferring to a wire rack.",
                            MealType = "[\"Snack\",\"Dessert\"]",
                            Name = "Chocolate Chip Cookies",
                            PrepTimeMinutes = 15,
                            Rating = 4.9f,
                            Servings = 24,
                            Tags = "Cookies\nDessert\nBaking",
                            UserId = 34
                        },
                        new
                        {
                            Id = 4L,
                            CaloriesPerServing = 500,
                            CookTimeMinutes = 20,
                            Cuisine = "Italian",
                            Difficulty = 1,
                            ImageUrl = "https://cdn.dummyjson.com/recipe-images/4.webp",
                            Ingredients = "Fettuccine pasta\nChicken breast, sliced\nHeavy cream\nParmesan cheese, grated\nGarlic, minced\nButter\nSalt and pepper to taste\nFresh parsley for garnish",
                            Instructions = "Cook fettuccine pasta according to package instructions.\nIn a pan, sauté sliced chicken in butter until fully cooked.\nAdd minced garlic and cook until fragrant.\nPour in heavy cream and grated Parmesan cheese. Stir until the cheese is melted.\nSeason with salt and pepper to taste.\nCombine the Alfredo sauce with cooked pasta.\nGarnish with fresh parsley before serving.",
                            MealType = "[\"Lunch\",\"Dinner\"]",
                            Name = "Chicken Alfredo Pasta",
                            PrepTimeMinutes = 15,
                            Rating = 4.9f,
                            Servings = 4,
                            Tags = "Pasta\nChicken",
                            UserId = 136
                        },
                        new
                        {
                            Id = 5L,
                            CaloriesPerServing = 380,
                            CookTimeMinutes = 25,
                            Cuisine = "Mexican",
                            Difficulty = 0,
                            ImageUrl = "https://cdn.dummyjson.com/recipe-images/5.webp",
                            Ingredients = "Chicken thighs\nMango, diced\nRed onion, finely chopped\nCilantro, chopped\nLime juice\nJalapeño, minced\nSalt and pepper to taste\nCooked rice for serving",
                            Instructions = "Season chicken thighs with salt and pepper.\nGrill or bake chicken until fully cooked.\nIn a bowl, combine diced mango, chopped red onion, cilantro, minced jalapeño, and lime juice.\nDice the cooked chicken and mix it with the mango salsa.\nServe over cooked rice.",
                            MealType = "[\"Dinner\"]",
                            Name = "Mango Salsa Chicken",
                            PrepTimeMinutes = 15,
                            Rating = 4.9f,
                            Servings = 3,
                            Tags = "Chicken\nSalsa",
                            UserId = 26
                        },
                        new
                        {
                            Id = 6L,
                            CaloriesPerServing = 280,
                            CookTimeMinutes = 15,
                            Cuisine = "Mediterranean",
                            Difficulty = 0,
                            ImageUrl = "https://cdn.dummyjson.com/recipe-images/6.webp",
                            Ingredients = "Quinoa, cooked\nAvocado, diced\nCherry tomatoes, halved\nCucumber, diced\nRed bell pepper, diced\nFeta cheese, crumbled\nLemon vinaigrette dressing\nSalt and pepper to taste",
                            Instructions = "In a large bowl, combine cooked quinoa, diced avocado, halved cherry tomatoes, diced cucumber, diced red bell pepper, and crumbled feta cheese.\nDrizzle with lemon vinaigrette dressing and toss to combine.\nSeason with salt and pepper to taste.\nChill in the refrigerator before serving.",
                            MealType = "[\"Lunch\",\"Side Dish\"]",
                            Name = "Quinoa Salad with Avocado",
                            PrepTimeMinutes = 20,
                            Rating = 4.4f,
                            Servings = 4,
                            Tags = "Salad\nQuinoa",
                            UserId = 197
                        },
                        new
                        {
                            Id = 7L,
                            CaloriesPerServing = 120,
                            CookTimeMinutes = 10,
                            Cuisine = "Italian",
                            Difficulty = 0,
                            ImageUrl = "https://cdn.dummyjson.com/recipe-images/7.webp",
                            Ingredients = "Baguette, sliced\nTomatoes, diced\nFresh basil, chopped\nGarlic cloves, minced\nBalsamic glaze\nOlive oil\nSalt and pepper to taste",
                            Instructions = "Preheat the oven to 375°F (190°C).\nPlace baguette slices on a baking sheet and toast in the oven until golden brown.\nIn a bowl, combine diced tomatoes, chopped fresh basil, minced garlic, and a drizzle of olive oil.\nSeason with salt and pepper to taste.\nTop each toasted baguette slice with the tomato-basil mixture.\nDrizzle with balsamic glaze before serving.",
                            MealType = "[\"Appetizer\"]",
                            Name = "Tomato Basil Bruschetta",
                            PrepTimeMinutes = 15,
                            Rating = 4.7f,
                            Servings = 6,
                            Tags = "Bruschetta\nItalian",
                            UserId = 137
                        },
                        new
                        {
                            Id = 8L,
                            CaloriesPerServing = 380,
                            CookTimeMinutes = 15,
                            Cuisine = "Asian",
                            Difficulty = 1,
                            ImageUrl = "https://cdn.dummyjson.com/recipe-images/8.webp",
                            Ingredients = "Beef sirloin, thinly sliced\nBroccoli florets\nSoy sauce\nOyster sauce\nSesame oil\nGarlic, minced\nGinger, minced\nCornstarch\nCooked white rice for serving",
                            Instructions = "In a bowl, mix soy sauce, oyster sauce, sesame oil, and cornstarch to create the sauce.\nIn a wok, stir-fry thinly sliced beef until browned. Remove from the wok.\nStir-fry broccoli florets, minced garlic, and minced ginger in the same wok.\nAdd the cooked beef back to the wok and pour the sauce over the mixture.\nStir until everything is coated and heated through.\nServe over cooked white rice.",
                            MealType = "[\"Dinner\"]",
                            Name = "Beef and Broccoli Stir-Fry",
                            PrepTimeMinutes = 20,
                            Rating = 4.7f,
                            Servings = 4,
                            Tags = "Beef\nStir-fry\nAsian",
                            UserId = 18
                        },
                        new
                        {
                            Id = 9L,
                            CaloriesPerServing = 200,
                            CookTimeMinutes = 0,
                            Cuisine = "Italian",
                            Difficulty = 0,
                            ImageUrl = "https://cdn.dummyjson.com/recipe-images/9.webp",
                            Ingredients = "Tomatoes, sliced\nFresh mozzarella cheese, sliced\nFresh basil leaves\nBalsamic glaze\nExtra virgin olive oil\nSalt and pepper to taste",
                            Instructions = "Arrange alternating slices of tomatoes and fresh mozzarella on a serving platter.\nTuck fresh basil leaves between the slices.\nDrizzle with balsamic glaze and extra virgin olive oil.\nSeason with salt and pepper to taste.\nServe immediately as a refreshing salad.",
                            MealType = "[\"Lunch\"]",
                            Name = "Caprese Salad",
                            PrepTimeMinutes = 10,
                            Rating = 4.6f,
                            Servings = 2,
                            Tags = "Salad\nCaprese",
                            UserId = 128
                        },
                        new
                        {
                            Id = 10L,
                            CaloriesPerServing = 400,
                            CookTimeMinutes = 20,
                            Cuisine = "Italian",
                            Difficulty = 1,
                            ImageUrl = "https://cdn.dummyjson.com/recipe-images/10.webp",
                            Ingredients = "Linguine pasta\nShrimp, peeled and deveined\nGarlic, minced\nWhite wine\nLemon juice\nRed pepper flakes\nFresh parsley, chopped\nSalt and pepper to taste",
                            Instructions = "Cook linguine pasta according to package instructions.\nIn a skillet, sauté minced garlic in olive oil until fragrant.\nAdd shrimp and cook until pink and opaque.\nPour in white wine and lemon juice. Simmer until the sauce slightly thickens.\nSeason with red pepper flakes, salt, and pepper.\nToss cooked linguine in the shrimp scampi sauce.\nGarnish with chopped fresh parsley before serving.",
                            MealType = "[\"Dinner\"]",
                            Name = "Shrimp Scampi Pasta",
                            PrepTimeMinutes = 15,
                            Rating = 4.3f,
                            Servings = 3,
                            Tags = "Pasta\nShrimp",
                            UserId = 114
                        },
                        new
                        {
                            Id = 11L,
                            CaloriesPerServing = 550,
                            CookTimeMinutes = 45,
                            Cuisine = "Pakistani",
                            Difficulty = 1,
                            ImageUrl = "https://cdn.dummyjson.com/recipe-images/11.webp",
                            Ingredients = "Basmati rice\nChicken, cut into pieces\nOnions, thinly sliced\nTomatoes, chopped\nYogurt\nGinger-garlic paste\nBiryani masala\nGreen chilies, sliced\nFresh coriander leaves\nMint leaves\nGhee\nSalt to taste",
                            Instructions = "Marinate chicken with yogurt, ginger-garlic paste, biryani masala, and salt.\nIn a pot, sauté sliced onions until golden brown. Remove half for later use.\nLayer marinated chicken, chopped tomatoes, half of the fried onions, and rice in the pot.\nTop with ghee, green chilies, fresh coriander leaves, mint leaves, and the remaining fried onions.\nCover and cook on low heat until the rice is fully cooked and aromatic.\nServe hot, garnished with additional coriander and mint leaves.",
                            MealType = "[\"Lunch\",\"Dinner\"]",
                            Name = "Chicken Biryani",
                            PrepTimeMinutes = 30,
                            Rating = 5f,
                            Servings = 6,
                            Tags = "Biryani\nChicken\nMain course\nIndian\nPakistani\nAsian",
                            UserId = 133
                        },
                        new
                        {
                            Id = 12L,
                            CaloriesPerServing = 420,
                            CookTimeMinutes = 30,
                            Cuisine = "Pakistani",
                            Difficulty = 0,
                            ImageUrl = "https://cdn.dummyjson.com/recipe-images/12.webp",
                            Ingredients = "Chicken, cut into pieces\nTomatoes, chopped\nGreen chilies, sliced\nGinger, julienned\nGarlic, minced\nCoriander powder\nCumin powder\nRed chili powder\nGaram masala\nCooking oil\nFresh coriander leaves\nSalt to taste",
                            Instructions = "In a wok (karahi), heat cooking oil and sauté minced garlic until golden brown.\nAdd chicken pieces and cook until browned on all sides.\nAdd chopped tomatoes, green chilies, ginger, and spices. Cook until tomatoes are soft.\nCover and simmer until the chicken is tender and the oil separates from the masala.\nGarnish with fresh coriander leaves and serve hot with naan or rice.",
                            MealType = "[\"Lunch\",\"Dinner\"]",
                            Name = "Chicken Karahi",
                            PrepTimeMinutes = 20,
                            Rating = 4.8f,
                            Servings = 4,
                            Tags = "Chicken\nKarahi\nMain course\nIndian\nPakistani\nAsian",
                            UserId = 49
                        },
                        new
                        {
                            Id = 13L,
                            CaloriesPerServing = 380,
                            CookTimeMinutes = 35,
                            Cuisine = "Pakistani",
                            Difficulty = 1,
                            ImageUrl = "https://cdn.dummyjson.com/recipe-images/13.webp",
                            Ingredients = "Ground beef\nPotatoes, peeled and diced\nOnions, finely chopped\nTomatoes, chopped\nGinger-garlic paste\nCumin powder\nCoriander powder\nTurmeric powder\nRed chili powder\nCooking oil\nFresh coriander leaves\nSalt to taste",
                            Instructions = "In a pan, heat cooking oil and sauté chopped onions until golden brown.\nAdd ginger-garlic paste and sauté until fragrant.\nAdd ground beef and cook until browned. Drain excess oil if needed.\nAdd diced potatoes, chopped tomatoes, and spices. Mix well.\nCover and simmer until the potatoes are tender and the masala is well-cooked.\nGarnish with fresh coriander leaves and serve hot with naan or rice.",
                            MealType = "[\"Lunch\",\"Dinner\"]",
                            Name = "Aloo Keema",
                            PrepTimeMinutes = 25,
                            Rating = 4.6f,
                            Servings = 5,
                            Tags = "Keema\nPotatoes\nMain course\nPakistani\nAsian",
                            UserId = 152
                        },
                        new
                        {
                            Id = 14L,
                            CaloriesPerServing = 320,
                            CookTimeMinutes = 20,
                            Cuisine = "Pakistani",
                            Difficulty = 1,
                            ImageUrl = "https://cdn.dummyjson.com/recipe-images/14.webp",
                            Ingredients = "Ground beef\nOnions, finely chopped\nTomatoes, finely chopped\nGreen chilies, chopped\nCoriander leaves, chopped\nPomegranate seeds\nGinger-garlic paste\nCumin powder\nCoriander powder\nRed chili powder\nEgg\nCooking oil\nSalt to taste",
                            Instructions = "In a large bowl, mix ground beef, chopped onions, tomatoes, green chilies, coriander leaves, and pomegranate seeds.\nAdd ginger-garlic paste, cumin powder, coriander powder, red chili powder, and salt. Mix well.\nAdd an egg to bind the mixture and form into round flat kebabs.\nHeat cooking oil in a pan and shallow fry the kebabs until browned on both sides.\nServe hot with naan or mint chutney.",
                            MealType = "[\"Lunch\",\"Dinner\",\"Snacks\"]",
                            Name = "Chapli Kebabs",
                            PrepTimeMinutes = 30,
                            Rating = 4.7f,
                            Servings = 4,
                            Tags = "Kebabs\nBeef\nIndian\nPakistani\nAsian",
                            UserId = 152
                        },
                        new
                        {
                            Id = 15L,
                            CaloriesPerServing = 280,
                            CookTimeMinutes = 30,
                            Cuisine = "Pakistani",
                            Difficulty = 1,
                            ImageUrl = "https://cdn.dummyjson.com/recipe-images/15.webp",
                            Ingredients = "Mustard greens, washed and chopped\nSpinach, washed and chopped\nCornmeal (makki ka atta)\nOnions, finely chopped\nGreen chilies, chopped\nGinger, grated\nGhee\nSalt to taste",
                            Instructions = "Boil mustard greens and spinach until tender. Drain and blend into a coarse paste.\nIn a pan, sauté chopped onions, green chilies, and grated ginger in ghee until golden brown.\nAdd the greens paste and cook until it thickens.\nMeanwhile, knead cornmeal with water to make a dough. Roll into rotis (flatbreads).\nCook the rotis on a griddle until golden brown.\nServe hot saag with makki di roti and a dollop of ghee.",
                            MealType = "[\"Breakfast\",\"Lunch\",\"Dinner\"]",
                            Name = "Saag (Spinach) with Makki di Roti",
                            PrepTimeMinutes = 40,
                            Rating = 4.3f,
                            Servings = 3,
                            Tags = "Saag\nRoti\nMain course\nIndian\nPakistani\nAsian",
                            UserId = 43
                        },
                        new
                        {
                            Id = 16L,
                            CaloriesPerServing = 480,
                            CookTimeMinutes = 25,
                            Cuisine = "Japanese",
                            Difficulty = 1,
                            ImageUrl = "https://cdn.dummyjson.com/recipe-images/16.webp",
                            Ingredients = "Ramen noodles\nChicken broth\nSoy sauce\nMirin\nSesame oil\nShiitake mushrooms, sliced\nBok choy, chopped\nGreen onions, sliced\nSoft-boiled eggs\nGrilled chicken slices\nNorwegian seaweed (nori)",
                            Instructions = "Cook ramen noodles according to package instructions and set aside.\nIn a pot, combine chicken broth, soy sauce, mirin, and sesame oil. Bring to a simmer.\nAdd sliced shiitake mushrooms and chopped bok choy. Cook until vegetables are tender.\nDivide the cooked noodles into serving bowls and ladle the hot broth over them.\nTop with green onions, soft-boiled eggs, grilled chicken slices, and nori.\nServe hot and enjoy the authentic Japanese ramen!",
                            MealType = "[\"Dinner\"]",
                            Name = "Japanese Ramen Soup",
                            PrepTimeMinutes = 20,
                            Rating = 4.9f,
                            Servings = 2,
                            Tags = "Ramen\nJapanese\nSoup\nAsian",
                            UserId = 85
                        },
                        new
                        {
                            Id = 17L,
                            CaloriesPerServing = 320,
                            CookTimeMinutes = 30,
                            Cuisine = "Moroccan",
                            Difficulty = 0,
                            ImageUrl = "https://cdn.dummyjson.com/recipe-images/17.webp",
                            Ingredients = "Chickpeas, cooked\nTomatoes, chopped\nCarrots, diced\nOnions, finely chopped\nGarlic, minced\nCumin\nCoriander\nCinnamon\nPaprika\nVegetable broth\nOlives\nFresh cilantro, chopped",
                            Instructions = "In a tagine or large pot, sauté chopped onions and minced garlic until softened.\nAdd diced carrots, chopped tomatoes, and cooked chickpeas.\nSeason with cumin, coriander, cinnamon, and paprika. Stir to coat.\nPour in vegetable broth and bring to a simmer. Cook until carrots are tender.\nStir in olives and garnish with fresh cilantro before serving.\nServe this flavorful Moroccan dish with couscous or crusty bread.",
                            MealType = "[\"Dinner\"]",
                            Name = "Moroccan Chickpea Tagine",
                            PrepTimeMinutes = 15,
                            Rating = 4.5f,
                            Servings = 4,
                            Tags = "Tagine\nChickpea\nMoroccan",
                            UserId = 207
                        },
                        new
                        {
                            Id = 18L,
                            CaloriesPerServing = 550,
                            CookTimeMinutes = 20,
                            Cuisine = "Korean",
                            Difficulty = 1,
                            ImageUrl = "https://cdn.dummyjson.com/recipe-images/18.webp",
                            Ingredients = "Cooked white rice\nBeef bulgogi (marinated and grilled beef slices)\nCarrots, julienned and sautéed\nSpinach, blanched and seasoned\nZucchini, sliced and grilled\nBean sprouts, blanched\nFried egg\nGochujang (Korean red pepper paste)\nSesame oil\nToasted sesame seeds",
                            Instructions = "Arrange cooked white rice in a bowl.\nTop with beef bulgogi, sautéed carrots, seasoned spinach, grilled zucchini, and blanched bean sprouts.\nPlace a fried egg on top and drizzle with gochujang and sesame oil.\nSprinkle with toasted sesame seeds before serving.\nMix everything together before enjoying this delicious Korean bibimbap!\nFeel free to customize with additional vegetables or protein.",
                            MealType = "[\"Dinner\"]",
                            Name = "Korean Bibimbap",
                            PrepTimeMinutes = 30,
                            Rating = 4.9f,
                            Servings = 2,
                            Tags = "Bibimbap\nKorean\nRice",
                            UserId = 121
                        },
                        new
                        {
                            Id = 19L,
                            CaloriesPerServing = 420,
                            CookTimeMinutes = 45,
                            Cuisine = "Greek",
                            Difficulty = 1,
                            ImageUrl = "https://cdn.dummyjson.com/recipe-images/19.webp",
                            Ingredients = "Eggplants, sliced\nGround lamb or beef\nOnions, finely chopped\nGarlic, minced\nTomatoes, crushed\nRed wine\nCinnamon\nAllspice\nNutmeg\nOlive oil\nMilk\nFlour\nParmesan cheese\nEgg yolks",
                            Instructions = "Preheat oven to 375°F (190°C).\nSauté sliced eggplants in olive oil until browned. Set aside.\nIn the same pan, cook chopped onions and minced garlic until softened.\nAdd ground lamb or beef and brown. Stir in crushed tomatoes, red wine, and spices.\nIn a separate saucepan, make béchamel sauce: melt butter, whisk in flour, add milk, and cook until thickened.\nRemove from heat and stir in Parmesan cheese and egg yolks.\nIn a baking dish, layer eggplants and meat mixture. Top with béchamel sauce.\nBake for 40-45 minutes until golden brown. Let it cool before slicing.\nServe slices of moussaka warm and enjoy this Greek classic!",
                            MealType = "[\"Dinner\"]",
                            Name = "Greek Moussaka",
                            PrepTimeMinutes = 45,
                            Rating = 4.3f,
                            Servings = 6,
                            Tags = "Moussaka\nGreek",
                            UserId = 173
                        },
                        new
                        {
                            Id = 20L,
                            CaloriesPerServing = 480,
                            CookTimeMinutes = 25,
                            Cuisine = "Pakistani",
                            Difficulty = 1,
                            ImageUrl = "https://cdn.dummyjson.com/recipe-images/20.webp",
                            Ingredients = "Chicken thighs, boneless and skinless\nYogurt\nGinger-garlic paste\nGaram masala\nKashmiri red chili powder\nTomato puree\nButter\nHeavy cream\nKasuri methi (dried fenugreek leaves)\nSugar\nSalt to taste",
                            Instructions = "Marinate chicken thighs in a mixture of yogurt, ginger-garlic paste, garam masala, and Kashmiri red chili powder.\nIn a pan, melt butter and sauté the marinated chicken until browned.\nAdd tomato puree and cook until the oil separates. Stir in heavy cream.\nSprinkle kasuri methi, sugar, and salt. Simmer until the chicken is fully cooked.\nServe this creamy butter chicken over rice or with naan for an authentic Pakistani/Indian experience.",
                            MealType = "[\"Dinner\"]",
                            Name = "Butter Chicken (Murgh Makhani)",
                            PrepTimeMinutes = 30,
                            Rating = 4.5f,
                            Servings = 4,
                            Tags = "Butter chicken\nCurry\nIndian\nPakistani\nAsian",
                            UserId = 138
                        },
                        new
                        {
                            Id = 21L,
                            CaloriesPerServing = 480,
                            CookTimeMinutes = 30,
                            Cuisine = "Thai",
                            Difficulty = 1,
                            ImageUrl = "https://cdn.dummyjson.com/recipe-images/21.webp",
                            Ingredients = "Chicken thighs, boneless and skinless\nGreen curry paste\nCoconut milk\nFish sauce\nSugar\nEggplant, sliced\nBell peppers, sliced\nBasil leaves\nJasmine rice for serving",
                            Instructions = "In a pot, simmer green curry paste in coconut milk.\nAdd chicken, fish sauce, and sugar. Cook until chicken is tender.\nStir in sliced eggplant and bell peppers. Simmer until vegetables are cooked.\nGarnish with fresh basil leaves.\nServe hot over jasmine rice and enjoy this Thai classic!",
                            MealType = "[\"Dinner\"]",
                            Name = "Thai Green Curry",
                            PrepTimeMinutes = 20,
                            Rating = 4.2f,
                            Servings = 4,
                            Tags = "Curry\nThai",
                            UserId = 153
                        },
                        new
                        {
                            Id = 22L,
                            CaloriesPerServing = 180,
                            CookTimeMinutes = 0,
                            Cuisine = "Indian",
                            Difficulty = 0,
                            ImageUrl = "https://cdn.dummyjson.com/recipe-images/22.webp",
                            Ingredients = "Ripe mango, peeled and diced\nYogurt\nMilk\nHoney\nCardamom powder\nIce cubes",
                            Instructions = "In a blender, combine diced mango, yogurt, milk, honey, and cardamom powder.\nBlend until smooth and creamy.\nAdd ice cubes and blend again until the lassi is chilled.\nPour into glasses and garnish with a sprinkle of cardamom.\nEnjoy this refreshing Mango Lassi!",
                            MealType = "[\"Beverage\"]",
                            Name = "Mango Lassi",
                            PrepTimeMinutes = 10,
                            Rating = 4.7f,
                            Servings = 2,
                            Tags = "Lassi\nMango\nIndian\nPakistani\nAsian",
                            UserId = 76
                        },
                        new
                        {
                            Id = 23L,
                            CaloriesPerServing = 350,
                            CookTimeMinutes = 0,
                            Cuisine = "Italian",
                            Difficulty = 1,
                            ImageUrl = "https://cdn.dummyjson.com/recipe-images/23.webp",
                            Ingredients = "Espresso, brewed and cooled\nLadyfinger cookies\nMascarpone cheese\nHeavy cream\nSugar\nCocoa powder",
                            Instructions = "In a bowl, whip heavy cream until stiff peaks form.\nIn another bowl, mix mascarpone cheese and sugar until smooth.\nGently fold the whipped cream into the mascarpone mixture.\nDip ladyfinger cookies into brewed espresso and layer them in a serving dish.\nSpread a layer of the mascarpone mixture over the cookies.\nRepeat layers and finish with a dusting of cocoa powder.\nChill in the refrigerator for a few hours before serving.\nIndulge in the decadence of this classic Italian Tiramisu!",
                            MealType = "[\"Dessert\"]",
                            Name = "Italian Tiramisu",
                            PrepTimeMinutes = 30,
                            Rating = 4.6f,
                            Servings = 6,
                            Tags = "Tiramisu\nItalian",
                            UserId = 130
                        },
                        new
                        {
                            Id = 24L,
                            CaloriesPerServing = 280,
                            CookTimeMinutes = 15,
                            Cuisine = "Turkish",
                            Difficulty = 0,
                            ImageUrl = "https://cdn.dummyjson.com/recipe-images/24.webp",
                            Ingredients = "Ground lamb or beef\nOnions, grated\nGarlic, minced\nParsley, finely chopped\nCumin\nCoriander\nRed pepper flakes\nSalt and pepper to taste\nFlatbread for serving\nTahini sauce",
                            Instructions = "In a bowl, mix ground meat, grated onions, minced garlic, chopped parsley, and spices.\nForm the mixture into kebab shapes and grill until fully cooked.\nServe the kebabs on flatbread with a drizzle of tahini sauce.\nEnjoy these flavorful Turkish Kebabs with your favorite sides.",
                            MealType = "[\"Dinner\"]",
                            Name = "Turkish Kebabs",
                            PrepTimeMinutes = 25,
                            Rating = 4.6f,
                            Servings = 4,
                            Tags = "Kebabs\nTurkish\nGrilling",
                            UserId = 26
                        },
                        new
                        {
                            Id = 25L,
                            CaloriesPerServing = 220,
                            CookTimeMinutes = 0,
                            Cuisine = "Smoothie",
                            Difficulty = 0,
                            ImageUrl = "https://cdn.dummyjson.com/recipe-images/25.webp",
                            Ingredients = "Blueberries, fresh or frozen\nBanana, peeled and sliced\nGreek yogurt\nAlmond milk\nHoney\nChia seeds (optional)",
                            Instructions = "In a blender, combine blueberries, banana, Greek yogurt, almond milk, and honey.\nBlend until smooth and creamy.\nAdd chia seeds for extra nutrition and blend briefly.\nPour into a glass and enjoy this nutritious Blueberry Banana Smoothie!",
                            MealType = "[\"Breakfast\",\"Beverage\"]",
                            Name = "Blueberry Banana Smoothie",
                            PrepTimeMinutes = 10,
                            Rating = 4.8f,
                            Servings = 1,
                            Tags = "Smoothie\nBlueberry\nBanana",
                            UserId = 16
                        },
                        new
                        {
                            Id = 26L,
                            CaloriesPerServing = 180,
                            CookTimeMinutes = 15,
                            Cuisine = "Mexican",
                            Difficulty = 0,
                            ImageUrl = "https://cdn.dummyjson.com/recipe-images/26.webp",
                            Ingredients = "Corn on the cob\nMayonnaise\nCotija cheese, crumbled\nChili powder\nLime wedges",
                            Instructions = "Grill or roast corn on the cob until kernels are charred.\nBrush each cob with mayonnaise, then sprinkle with crumbled Cotija cheese and chili powder.\nServe with lime wedges for squeezing over the top.\nEnjoy this delicious and flavorful Mexican Street Corn!",
                            MealType = "[\"Snack\",\"Side Dish\"]",
                            Name = "Mexican Street Corn (Elote)",
                            PrepTimeMinutes = 15,
                            Rating = 4.6f,
                            Servings = 4,
                            Tags = "Elote\nMexican\nStreet food",
                            UserId = 93
                        },
                        new
                        {
                            Id = 27L,
                            CaloriesPerServing = 220,
                            CookTimeMinutes = 40,
                            Cuisine = "Russian",
                            Difficulty = 1,
                            ImageUrl = "https://cdn.dummyjson.com/recipe-images/27.webp",
                            Ingredients = "Beets, peeled and shredded\nCabbage, shredded\nPotatoes, diced\nOnions, finely chopped\nCarrots, grated\nTomato paste\nBeef or vegetable broth\nGarlic, minced\nBay leaves\nSour cream for serving",
                            Instructions = "In a pot, sauté chopped onions and garlic until softened.\nAdd shredded beets, cabbage, diced potatoes, grated carrots, and tomato paste.\nPour in broth and add bay leaves. Simmer until vegetables are tender.\nServe hot with a dollop of sour cream on top.\nEnjoy the hearty and comforting flavors of Russian Borscht!",
                            MealType = "[\"Dinner\"]",
                            Name = "Russian Borscht",
                            PrepTimeMinutes = 30,
                            Rating = 4.3f,
                            Servings = 6,
                            Tags = "Borscht\nRussian\nSoup",
                            UserId = 1
                        },
                        new
                        {
                            Id = 28L,
                            CaloriesPerServing = 320,
                            CookTimeMinutes = 20,
                            Cuisine = "Indian",
                            Difficulty = 1,
                            ImageUrl = "https://cdn.dummyjson.com/recipe-images/28.webp",
                            Ingredients = "Dosa batter (fermented rice and urad dal batter)\nPotatoes, boiled and mashed\nOnions, finely chopped\nMustard seeds\nCumin seeds\nCurry leaves\nTurmeric powder\nGreen chilies, chopped\nGhee\nCoconut chutney for serving",
                            Instructions = "In a pan, heat ghee and add mustard seeds, cumin seeds, and curry leaves.\nAdd chopped onions, green chilies, and turmeric powder. Sauté until onions are golden brown.\nMix in boiled and mashed potatoes. Cook until well combined and seasoned.\nSpread dosa batter on a hot griddle to make thin pancakes.\nPlace a spoonful of the potato mixture in the center, fold, and serve hot.\nPair with coconut chutney for a delicious South Indian meal.",
                            MealType = "[\"Breakfast\"]",
                            Name = "South Indian Masala Dosa",
                            PrepTimeMinutes = 40,
                            Rating = 4.4f,
                            Servings = 4,
                            Tags = "Dosa\nIndian\nAsian",
                            UserId = 138
                        },
                        new
                        {
                            Id = 29L,
                            CaloriesPerServing = 400,
                            CookTimeMinutes = 10,
                            Cuisine = "Lebanese",
                            Difficulty = 0,
                            ImageUrl = "https://cdn.dummyjson.com/recipe-images/29.webp",
                            Ingredients = "Falafel balls\nWhole wheat or regular wraps\nTomatoes, diced\nCucumbers, sliced\nRed onions, thinly sliced\nLettuce, shredded\nTahini sauce\nFresh parsley, chopped",
                            Instructions = "Warm falafel balls according to package instructions.\nPlace a generous serving of falafel in the center of each wrap.\nTop with diced tomatoes, sliced cucumbers, red onions, shredded lettuce, and fresh parsley.\nDrizzle with tahini sauce and wrap tightly.\nEnjoy this Lebanese Falafel Wrap filled with fresh and flavorful ingredients!",
                            MealType = "[\"Lunch\"]",
                            Name = "Lebanese Falafel Wrap",
                            PrepTimeMinutes = 15,
                            Rating = 4.7f,
                            Servings = 2,
                            Tags = "Falafel\nLebanese\nWrap",
                            UserId = 110
                        },
                        new
                        {
                            Id = 30L,
                            CaloriesPerServing = 150,
                            CookTimeMinutes = 0,
                            Cuisine = "Brazilian",
                            Difficulty = 0,
                            ImageUrl = "https://cdn.dummyjson.com/recipe-images/30.webp",
                            Ingredients = "Cachaça (Brazilian sugarcane spirit)\nLime, cut into wedges\nGranulated sugar\nIce cubes",
                            Instructions = "In a glass, muddle lime wedges with granulated sugar to release the juice.\nFill the glass with ice cubes.\nPour cachaça over the ice and stir well.\nSip and enjoy the refreshing taste of the Brazilian Caipirinha!\nAdjust sugar and lime to suit your taste preferences.",
                            MealType = "[\"Beverage\"]",
                            Name = "Brazilian Caipirinha",
                            PrepTimeMinutes = 5,
                            Rating = 4.4f,
                            Servings = 1,
                            Tags = "Caipirinha\nBrazilian\nCocktail",
                            UserId = 134
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BusinessLogic.Models.OrderItem", b =>
                {
                    b.HasOne("BusinessLogic.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessLogic.Models.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BusinessLogic.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BusinessLogic.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessLogic.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BusinessLogic.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BusinessLogic.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
